USE [master]
GO

/****** Object:  Database [GYM_Manager_DB]    Script Date: 07/05/2023 5:08:40 CH ******/
CREATE DATABASE [GYM_Manager_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GYM_Manager_DB_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GYM_Manager_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GYM_Manager_DB_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GYM_Manager_DB.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GYM_Manager_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GYM_Manager_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GYM_Manager_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GYM_Manager_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GYM_Manager_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GYM_Manager_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET RECOVERY FULL 
GO

ALTER DATABASE [GYM_Manager_DB] SET  MULTI_USER 
GO

ALTER DATABASE [GYM_Manager_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GYM_Manager_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GYM_Manager_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GYM_Manager_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GYM_Manager_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GYM_Manager_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GYM_Manager_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GYM_Manager_DB] SET  READ_WRITE 
GO

