//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYM_Manager_DBEntities : DbContext
    {
        public GYM_Manager_DBEntities()
            : base("name=GYM_Manager_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLOG> BLOG { get; set; }
        public virtual DbSet<CLUB> CLUB { get; set; }
        public virtual DbSet<DANGKYGOITAP> DANGKYGOITAP { get; set; }
        public virtual DbSet<DICHVU> DICHVU { get; set; }
        public virtual DbSet<GOITAP> GOITAP { get; set; }
        public virtual DbSet<GIAMGIA> GIAMGIA { get; set; }
        public virtual DbSet<KHOTHIETBI> KHOTHIETBI { get; set; }
        public virtual DbSet<LOAIBLOG> LOAIBLOG { get; set; }
        public virtual DbSet<LOAITHETHANHVIEN> LOAITHETHANHVIEN { get; set; }
        public virtual DbSet<LOAITHIETBI> LOAITHIETBI { get; set; }
        public virtual DbSet<NHAPTHIETBI> NHAPTHIETBI { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIEN { get; set; }
        public virtual DbSet<THETHANHVIEN> THETHANHVIEN { get; set; }
        public virtual DbSet<THIETBI> THIETBI { get; set; }
    }
}
